### ISSUE TITLE
All Elemental Storm Rares are missing :(

### ISSUE THREAD

**Issue by fubaWoW** [melroy999/RareTrackerDragonflight#1]
Hi there,
It seems every Rare from all the Elemental Storms are missing!

maybe you can use this source to add them:
https://www.wowhead.com/achievement=16461/stormed-off

there are all the rares with ID's and also Zones they spawn in.

Also made a Table if you need it
| Zone Name (English)  | NPC ID | NPC Name (English)  |
| --- | --- | --- |
The Azure Span | 193648 | Infernum
||||
The Waking Shores | 193644 | Bouldron
The Waking Shores | 193647 | Karantun
The Waking Shores | 193650 | Emblazion
The Waking Shores | 193650 | Gravlion
The Waking Shores | 193653 | Gaelzion
The Waking Shores | 193655 | Frozion
The Waking Shores | 193674 | Voraazka
The Waking Shores | 193675 | Kain Firebrand
The Waking Shores | 193677 | Maeleera
The Waking Shores | 193678 | Fieraan
The Waking Shores | 193679 | Leerain
The Waking Shores | 193682 | Rouen Icewind
The Waking Shores | 193684 | Pipspark Thundersnap
The Waking Shores | 193686 | Neela Firebane
||||
The Primalist Future | 193645 | Crystalus
The Primalist Future | 193652 | Grizzlerock
The Primalist Future | 193680 | Zurgaz Corebreaker

not 100% sure this are ALL of them but it's a "good start" anyway 🤣

**Comment by melroy999** [comment]
Ouch, thank you for bringing that to my attention. This is the first time I have attempted to make a module for an entire expansion instead of a single zone, and as you noticed, it is rather easy to make some oversights.

With that said though, from what I can gather, the rares that can spawn depend upon the type of elemental storm event correct? Therefore, I believe that they are not bound to a specific zone: that makes adding these rares quite complicated, since it would require 18 rares to be added to all of the individual zones. Consequentially, I am not sure if the window will still fit on everyone's screen.

I will see if I can somehow detect if/and which storm event is up to limit the number of rares that have to be displayed. Unfortunately, I cannot give an ETA, but I will take a look at it as soon as I am able.

**Comment by fubaWoW** [comment]
Yeah that is a good question -> "they are not bound to a specific zone"?

TBH i just don't know if all Rares can spawn in every Zone or some of them are Zone Specific even if there is the same Type of Storm...
I've not played/farmed the Storm Event that much to answer that correctly :D

**Comment by melroy999** [comment]
No problem! I am sure that I can find some clarifications on the matter on wowhead or the forums and see what is possible to implement based on that.
