### ISSUE TITLE
Game error taking taxi into Zaralek Caverns

### ISSUE THREAD

**Issue by mbattersby** [melroy999/RareTrackerDragonflight#2]
Every time I take the (flight path) taxi from Valdrakken to Loamm (Zaralek Caverns) I get this LUA error:

> Message: Usage: local vignettePosition, vignetteFacing = C_VignetteInfo.GetVignettePosition(vignetteGUID, uiMapID)
> Time: Mon May 15 14:13:00 2023
> Count: 1
> Stack: Usage: local vignettePosition, vignetteFacing = C_VignetteInfo.GetVignettePosition(vignetteGUID, uiMapID)
> [string "=[C]"]: in function `GetVignettePosition'
> [string "@Interface/AddOns/RareTrackerCore/RareTrackerCoreEventHandler.lua"]:270: in function `?'
> [string "@Interface/AddOns/RareTrackerCore/libs/LibDBIcon-1.0/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:119: in function <...Icon-1.0/CallbackHandler-1.0/CallbackHandler-1.0.lua:119>
> [string "=[C]"]: ?
> [string "@Interface/AddOns/RareTrackerCore/libs/LibDBIcon-1.0/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:29: in function <...Icon-1.0/CallbackHandler-1.0/CallbackHandler-1.0.lua:25>
> [string "@Interface/AddOns/RareTrackerCore/libs/LibDBIcon-1.0/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:64: in function `Fire'
> [string "@Interface/AddOns/RareTrackerCore/libs/AceEvent-3.0/AceEvent-3.0.lua"]:120: in function <...s/RareTrackerCore/libs/AceEvent-3.0/AceEvent-3.0.lua:119>
> 
> Locals: (*temporary) = "Usage: local vignettePosition, vignetteFacing = C_VignetteInfo.GetVignettePosition(vignetteGUID, uiMapID)"

The only two addons loaded are RareTrackerCore and RareTrackerDragonflight.

It doesn't happen with just RareTrackerCore loaded, it requires RareTrackerDragonflight.

It doesn't happen if I dragonride manually into Zaralek Caverns, only on the taxi.

It may be a bug in RareTrackerCore, but since it doesn't trigger unless RareTrackerDragonflight is loaded I have to post it here first.

It seems likely that there is a moment where :VIGNETTE_MINIMAP_UPDATED has fired but somehow C_Map.GetBestMapForUnit('player') is nil.

**Comment by melroy999** [comment]
Interesting, thank you for the report! The bug does indeed seem to be part of the RareTrackerCore addon. However, I am not sure whether C_Map.GetBestMapForUnit('player') being nil is the root issue in this particular case--specifically, it is interesting to note that the GetVignettePosition has two return values now instead of a single one. The latter does seem to be a change made in patch 10.1 that I was not aware of.

Nevertheless, I will try to reproduce the issue and find a way to fix said bug. Thanks again for the detailed bug report!

**Comment by melroy999** [comment]
Unfortunately, I have been unable to reproduce the issue in-game. However, I can confirm that your earlier hunch is likely correct, since a nil value substitute for the C_Map.GetBestMapForUnit('player') does produce the same function usage error. 

As such, I have added conditionals to check for said situation, in combination with having two return values as per the changes made in 10.1 to the GetVignettePosition function. Hopefully said measures fix the issue, but otherwise, don't hesitate to report further complications.
